### ISSUE TITLE
Issue form

### ISSUE THREAD

**Issue by hola-soy-milk** [distributeaid/distributeaid.org#353] opened 2022-06-20 17:47 UTC
Big fan of how OpenSauced first has a [form for a type of issue](https://github.com/open-sauced/open-sauced/issues/new/choose), followed by a [form for the issue itself](https://github.com/open-sauced/open-sauced/issues/new?assignees=&labels=%F0%9F%91%80+needs+triage%2C%F0%9F%90%9B+bug&template=bug_report.yml&title=Bug%3A+).

I'm especially a big fan of having the Code of Conduct be a required field to check, which is something we could have [for ours](https://github.com/distributeaid/.github/blob/saga/CODE_OF_CONDUCT.md).

**Comment by Nafisa-Huda** [comment] 2022-09-13 15:42
I'd like to be assigned to this.

**Comment by jtfairbank** [comment] 2022-09-13 18:07
All yours @Nafisa-Huda !  Let me know if you need any help, not sure if there are parts of this that require maintainer permissions for the repository, but I can handle that side for you.

Do [checkout our dev community events](https://opencollective.com/distribute-aid-usa/events) which provide a great way to connect with other folks working on Distribute Aid's open source projects!

### Our Issue Lifecycle

1. Issue is submitted and gets tagged as `triage`.  Would be cool if the `triage` tag could happen automatically.  Fine to add other tags as well at this stage.
2. A maintainer processes the issue, adding to it as needed. The `triage` tag is removed to indicate it's ready for work.
    - If the issue is a duplicate or not relevant, it'll get a `duplicate` or `wont-fix` tag at this step and be closed by the maintainer.
3. A contributor comments in the issue discussion that they'd like to tackle it, and gets assigned to it.
4. The contributor submits a draft PR and links the issue to the PR.
5. After development is complete the contributor upgrades the PR from a draft to a full PR.
6. A maintainer reviews the PR, possibly requesting changes from the contributor, then approves it once it's ready.  Finally, they merge the PR into our main branch, `saga`.
7. The issue can be closed at this point.
    - If there were reach goals / next steps that weren't addressed by the PR, new issues should be created to tackle those.
8. Everyone celebrates! :partying_face:

**Comment by Nafisa-Huda** [comment] 2022-09-14 01:25
Hi, I'm almost finished completing this issue.  For the "Ask a question" form, what specific URL do you want me to include? In the OpenSauced project "Ask a question" form, they have the link to their discord server.

**Comment by coderbyheart** [comment] 2022-09-14 06:15
You can link to https://github.com/distributeaid/distributeaid.org/discussions

**Comment by Nafisa-Huda** [comment] 2022-09-14 14:26
Thank you! Just made the pull request.

**Comment by coderbyheart** [comment] 2022-09-14 15:06
PR: #639

**Comment by fedechaves** [comment] 2023-01-17 02:00
hey @jtfairbank , this seems like it needs to be closed

**Closed as completed** 2023-05-01 01:35 UTC
Labels: help wanted
